# Generated by Django 4.2.2 on 2023-07-24 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('siglas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LocalRepuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=75)),
                ('total_mercaderia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales_repuestos_barrio', to='administrador.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales_repuestos_persona', to='administrador.persona')),
            ],
        ),
        migrations.CreateModel(
            name='LocalComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=75)),
                ('tipo_comida', models.CharField(max_length=50)),
                ('ventas_mes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales_comida_barrio', to='administrador.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales_comida_persona', to='administrador.persona')),
            ],
        ),
    ]
